server:
  port: 8082
spring:
  application:
    name: basicInfo
  datasource:
    url: jdbc:mysql://localhost:3306/basic_information?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qeen1013
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 600
        max-wait: 10000
        max-active: 300
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    service-url:
      defaultZone: http://${eureka_host:localhost}:${eureka_port:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redisprefix: basic-

fileUploadPath: /Users/yautumn/fileupload/
fileCreatePath: /Users/yautumn/filecreate/

logging:
  config: classpath:logback-spring.xml

shopMemerMax: 3